@echo off
del /f 
del /f E:\3DMM\obj\wins\splot.obj
del /f E:\3DMM\obj\wins\scnsort.obj
del /f E:\3DMM\obj\wins\browser.obj
del /f E:\3DMM\obj\wins\utest.obj
del /f E:\3DMM\obj\wins\stdioscb.obj
del /f E:\3DMM\obj\wins\stdiobrw.obj
del /f E:\3DMM\obj\wins\studio.obj
del /f E:\3DMM\obj\wins\tgob.obj
del /f E:\3DMM\obj\wins\esl.obj
del /f E:\3DMM\obj\wins\ape.obj
del /f E:\3DMM\obj\wins\popup.obj
del /f E:\3DMM\obj\wins\tatr.obj
del /f E:\3DMM\obj\wins\portf.obj
del /f E:\3DMM\obj\wins\mminstal.obj
del /f E:\3DMM\obj\wins\utest.res
del /f E:\3DMM\obj\wins\3dmovie.chk
