@echo off
del /f 
del /f H:\BUILD\SOC\obj\wind\splot.obj
del /f H:\BUILD\SOC\obj\wind\scnsort.obj
del /f H:\BUILD\SOC\obj\wind\browser.obj
del /f H:\BUILD\SOC\obj\wind\utest.obj
del /f H:\BUILD\SOC\obj\wind\stdioscb.obj
del /f H:\BUILD\SOC\obj\wind\stdiobrw.obj
del /f H:\BUILD\SOC\obj\wind\studio.obj
del /f H:\BUILD\SOC\obj\wind\tgob.obj
del /f H:\BUILD\SOC\obj\wind\esl.obj
del /f H:\BUILD\SOC\obj\wind\ape.obj
del /f H:\BUILD\SOC\obj\wind\popup.obj
del /f H:\BUILD\SOC\obj\wind\tatr.obj
del /f H:\BUILD\SOC\obj\wind\portf.obj
del /f H:\BUILD\SOC\obj\wind\utest.res
del /f H:\BUILD\SOC\obj\wind\3dmovie.chk
