#--- $(SOC_ROOT)\makefile.mak

!INCLUDE $(KAUAI_ROOT)\makefile.def

.SILENT:

# ALL: ALL_FMT ALL_FW ALL_ZB ALL_3DMM
ALL: ALL_FMT ALL_FW ALL_ZB ALL_3DMM

ALL_FMT:
    cd $(SOC_ROOT)\bren\fmt
    @echo Making brfm All...
    $(MAKE) /NOLOGO all
    cd $(SOC_ROOT)\bren
	
ALL_FW:
    cd $(SOC_ROOT)\bren\fw
    @echo Making brfw All...
    $(MAKE) /NOLOGO all
    cd $(SOC_ROOT)\bren

ALL_ZB:
    cd $(SOC_ROOT)\bren\zb
    @echo Making brzb All...
    $(MAKE) /NOLOGO all
    cd $(SOC_ROOT)\bren

ALL_3DMM:
    cd $(SOC_ROOT)\bren\3dmm
    @echo Making bren All...
    $(MAKE) /NOLOGO all
    cd $(SOC_ROOT)\bren

CLEAN: CLEAN_REST CLEAN_FMT CLEAN_FW CLEAN_ZB CLEAN_3DMM

CLEAN_FMT:
    cd $(SOC_ROOT)\bren\fmt
    @echo Cleaning brfm All...
    $(MAKE) /NOLOGO clean
    cd $(SOC_ROOT)\bren
	
CLEAN_FW:
    cd $(SOC_ROOT)\bren\fw
    @echo Cleaning brfw All...
    $(MAKE) /NOLOGO clean
    cd $(SOC_ROOT)\bren

CLEAN_ZB:
    cd $(SOC_ROOT)\bren\zb
    @echo Cleaning brzb All...
    $(MAKE) /NOLOGO clean
    cd $(SOC_ROOT)\bren

CLEAN_3DMM:
    cd $(SOC_ROOT)\bren\3dmm
    @echo Cleaning bren All...
    $(MAKE) /NOLOGO clean
    cd $(SOC_ROOT)\bren

CLEAN_REST:
    @echo Cleaning $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\ directory
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.obj 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.pch 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.pdb 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.exe 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.res 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.chk 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.cht 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.cod 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.map 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.thd 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.lib 2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.i   2>nul
    del /f $(SOC_ROOT)\bren\obj\$(BLD_TYPE_DIR)\*.lnk 2>nul